# Generated by Django 2.1.4 on 2019-01-09 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50, verbose_name='activity name')),
                ('activityTime', models.CharField(max_length=50, verbose_name='activity time')),
                ('activityType', models.CharField(max_length=50, verbose_name='activity type')),
                ('classifyAge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Age')),
                ('classifyStage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stage')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(max_length=50)),
                ('openAddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50, verbose_name='class name')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentName', models.CharField(max_length=100, verbose_name='parentName')),
                ('parentSurname', models.CharField(max_length=250)),
                ('parentDateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(choices=[('cash', 'CASH'), ('creditcard', 'CREDITCARD')], default='CASH', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(max_length=50, verbose_name='report name')),
                ('reportType', models.CharField(max_length=50, verbose_name='report type')),
                ('reportContent', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100, verbose_name='schoolname')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50, verbose_name='student name')),
                ('studentSurname', models.CharField(max_length=50, verbose_name='student surname')),
                ('studentDateOfBirth', models.DateField(max_length=50, verbose_name='student Date birth')),
                ('bookID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracking.Books', verbose_name='Book ')),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Parent', verbose_name='Parent')),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.School', verbose_name='School ')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Addresses', verbose_name='Address ID')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Student', verbose_name='student ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tracking.Users')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
            bases=('Tracking.users',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tracking.Users')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
            bases=('Tracking.users',),
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Student', verbose_name='student ID'),
        ),
    ]
