# Generated by Django 2.1.4 on 2019-01-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssActToStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Activities', verbose_name='activity id')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Student', verbose_name='student id')),
            ],
        ),
    ]
