# Generated by Django 2.1.4 on 2019-01-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_assacttostudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='studentID',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
