# Generated by Django 2.1.4 on 2019-01-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssActToTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Activities', verbose_name='activity id')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Teacher', verbose_name='teacher name')),
            ],
        ),
    ]
