# Generated by Django 2.1.4 on 2019-01-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_assacttoteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starTime', models.TimeField(verbose_name='start time')),
                ('endTime', models.TimeField(verbose_name='end time')),
                ('activityID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Activities', verbose_name='activity id')),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Classes', verbose_name='class id')),
            ],
        ),
    ]
