# Generated by Django 2.1.4 on 2019-01-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_classhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkName', models.CharField(max_length=100, verbose_name='homework name')),
                ('givenDate', models.DateField(verbose_name='given date')),
                ('dueDate', models.DateTimeField(verbose_name='due date')),
                ('assActToStuID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tracking.AssActToStudent', verbose_name='assigned activity id')),
            ],
        ),
    ]
