# Generated by Django 2.1.4 on 2019-01-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0008_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100, verbose_name='result')),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Exam', verbose_name='exam ID')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.Student', verbose_name='student ID')),
            ],
        ),
    ]
