# Generated by Django 2.1.4 on 2019-01-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0009_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='grade')),
                ('stage', models.CharField(max_length=50, verbose_name='stage')),
                ('examResultID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.ExamResult')),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Reports', verbose_name='report ID')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.Teacher')),
            ],
        ),
    ]
