# Generated by Django 2.1.4 on 2019-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0011_auto_20190110_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreport',
            name='content',
            field=models.TextField(default=1, verbose_name='content'),
            preserve_default=False,
        ),
    ]
