# Generated by Django 2.1.4 on 2019-01-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0013_auto_20190112_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreport',
            name='activityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.Activities'),
        ),
        migrations.AddField(
            model_name='teacherreport',
            name='studentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracking.Student'),
        ),
    ]
